Parameters:
  NameOfService:
    Description: Cylock instances
    Type: String
  KeyName:
    Description: existing key pairs to enable ssh access to server
    Type: AWS::EC2::KeyPair::KeyName
Mappings:
  RegionMap:
    us-west-2:
      AMI: ami-008c6427c8facbe08
Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags:
        - Key: "Name"
          Value: !Ref NameOfService
      Keyname: !Ref KeyName 
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
Outputs:
  ServerDNS:
    Value: !GetAtt 
      - Ec2Instance 
      - PublicDnsName