Resources:
 CylockS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead 
      BucketName: Cylocktestbucket
      CorsConfiguration: 
      LifecycleConfiguration: 
      NotificationConfiguration: 
      VersioningConfiguration: 
      WebsiteConfiguration: 
       IndexDocument: index.html
      Tags:
        - Key: Name
          Value: !Join [ "", [EC2, Instane, with, fn ,join ] ] 
  MySecurityGroup:
   paramName:
     Description: For static website
     Type: AWS::EC2::SecurityGroup::Id
     Properties:
      GroupDescription: Enable ssh via port 22
      SecurityGroupIngress:
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
      